services:
  - type: web
    name: link-shopee-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SHOPEE_PARTNER_ID
        sync: false
      - key: SHOPEE_PARTNER_KEY
        sync: false
